### PR TITLE
pdc command take release and name as parameters instead of id.

### PR DESCRIPTION
**Pull request by ycheng-aa**
JIRA: PDC-1159

### CODE REVIEW

**Comment by xychu** [comment]
:+1:

**Comment by ycheng-aa** [comment]
The output of a exception looks not so friendly for user. How about print the error message and exit(1). Could it report the error by exiting code?

**Comment by lubomir** [comment]
Printing the error and exitting would work as well. My main complaint is that the exit code should not be 0.

**Comment by ycheng-aa** [comment]
Rebase to eliminate CI failed.

**Comment by erichuanggit** [comment]
Looks good to me.

**Comment by lubomir** [comment]
:+1:

**Pull request merged**
