### PR TITLE
Correct warning message

### PR DESCRIPTION
**Pull request by erichuanggit**
Current release component is constraint by release and name but
without global component. It should not contain global component
as unique constraint field.

JIRA: PDC-1002

### CODE REVIEW

**Comment by simozhan** [comment]
+1

**Comment by lubomir** [comment]
Is the validator necessary at all? `ModelSerializer` should pick the unique constraint from the model directly.

**Comment by erichuanggit** [comment]
The `UniqueTogetherValidation` class always imposes an implicit constraint that all the fields it applies to are always treated as required.
Since we have `validate_global_component` validate function. Looks like it is not necessary. I will remove it.

**Comment by lubomir** [comment]
:+1:

**Comment by bliuredhat** [comment]
+1

**Pull request closed without merging**
