### PR TITLE
Keep track of reasons for changes.

### PR DESCRIPTION
**Pull request by simozhan**
As a user I want to keep track of reasons for changes

JIRA: PDC-923

### CODE REVIEW

**Comment by simozhan** [comment]
I changed the existing middleware test cases which made me feel not very good. Any good suggestion?

**Comment by erichuanggit** [comment]
is this supposed on `bulk`? if yes, could we add related test cases?

**Comment by simozhan** [comment]
I am assuming if the change is ok for create and bulk create. It should be ok for the other operations. right?

**Comment by lubomir** [comment]
This looks ok to me. I think it would be better to rename to field to {{change_comment}} or maybe just {{comment}}. There is no reason for the {{pdc_}} prefix. The reason why it is in the header name is so that it is clear that part of the HTTP request is PDC specific. But in database, everything is PDC related, so we don't need to explicitly prefix columns with that info.

**Comment by simozhan** [comment]
Yes. pdc prefix is not necessary. Fixing

**Comment by lubomir** [comment]
I found one more issue and one possible improvement:
 * the example for changeset list/retrieve API needs to be updated to display the field (response format section is correct)
 * it would be nice to add the comment to `pdc/apps/changeset/templates/changeset_detail.html`

**Comment by simozhan** [comment]
Thanks @lubomir for pointing out this issue. Totally forgot it. Fixed.

**Comment by lubomir** [comment]
:+1: Please squash the commits before merging.

**Pull request merged**
