### PR TITLE
Create read-only list of services, content formats, content categories.

### PR DESCRIPTION
**Pull request by simozhan**
And link to them from content-delivery-repos.

JIRA: PDC-917
      PDC-918
      PDC-919

### CODE REVIEW

**Comment by erichuanggit** [comment]
Looks good to me.

**Comment by lubomir** [comment]
:+1: I especially like the names for routes, it will help make it easier to understand when used somewhere. Maybe it could use some tests, although it is rather simple.

**Comment by simozhan** [comment]
Test cases added.

**Comment by simozhan** [comment]
Conflicts have been resolved in local branch, will be pushed when review is ok.

**Comment by lubomir** [comment]
This is definitely ready to be merged. By the way, you can `git push -f origin PDC-890_subtasks_917_9178_919` and it will re-run travis checks. But it is not necessary.

**Comment by simozhan** [comment]
thanks lubomir. push it.

**Pull request merged**
