### PR TITLE
Delete related methods should not be allowed in RPM API

### PR DESCRIPTION
**Pull request by ycheng-aa**
JIRA: PDC-936

### CODE REVIEW

**Comment by lubomir** [comment]
:+1:

**Comment by simozhan** [comment]
looks good to me

**Comment by erichuanggit** [comment]
Looks good to me.

**Comment by lubomir** [comment]
Merged as [3da45728](https://github.com/release-engineering/product-definition-center/commit/3da4572821e6daf58b9a543132b8e45c52392d36).

**Pull request closed without merging**
