### PR TITLE
Create role contact with non-existing role type is not allowed.

### PR DESCRIPTION
**Pull request by ycheng-aa**
JIRA: PDC-982

### CODE REVIEW

**Comment by lubomir** [comment]
I think it is still possible to to replicate the problem via component contacts:
```
pdc_client -s local -r release-components/1/contacts -x post -d '{"contact_role": "Buld_Owner", "contact": {…}}'
```

This should be fixed too.

**Comment by erichuanggit** [comment]
Other fixing should be in class `RoleContactSpecificManager` of contact.models

**Comment by erichuanggit** [comment]
@lubomir, I am not sure if we need to prevent this nested resource created. At lease it is not consistent. There are still some cases need to be improved as well. List some of them but not limited:
> Create a RoleContact with non existed Person `username` or Maillist `mail_name`, Person/Mailist will be created.

**Comment by lubomir** [comment]
You're right, the contact will also be created if it did not exist before. Maybe @sochotnicky can tell us what the correct behaviour should be.

**Comment by ycheng-aa** [comment]
Fixed in 4438e72f2702ec274e8631ee29bd. I kept the release-components/1/contacts behavior no touch on purpose. Now it should prevent this kind of indirect creation. But only for contact role now.

As discussed with @erichuanggit, if only prevent new contact role from being created, RoleContactSpecificManager don't have to be changed.

**Comment by simozhan** [comment]
I like the last commit. Only prevent new contact role from being created. +1

**Comment by lubomir** [comment]
I like it too. I never meant for person or maillist to not be created, just the contact role. Could the `ContactRoleField` be replaced with `ChoiceSlugField`? It would improve the error message.

**Comment by ycheng-aa** [comment]
Changed it to ChoiceSlugField. Then ContactRoleField became useless. Also removed it.

**Comment by lubomir** [comment]
:+1:

**Comment by erichuanggit** [comment]
Looks good to me.

**Pull request closed without merging**
