### PR TITLE
Add description to web ui

### PR DESCRIPTION
**Pull request by lubomir**
Each list page on the UI now has a help button. Clicking this button
displays a popup with description what the page represents.

JIRA: PDC-714

### CODE REVIEW

**Comment by simozhan** [comment]
Looks good to me.

**Comment by bliuredhat** [comment]
cool~! +1

**Comment by xychu** [comment]
:+1:

**Comment by erichuanggit** [comment]
Basically it looks good to me. But not sure if we need to add such description for `Archies` and `SigKeys`.

**Pull request merged**
