### PR TITLE
Add example script to find components with duplicate contacts

### PR DESCRIPTION
**Pull request by lubomir**
While this script is not terribly useful for day-to-day life, it can
serve as an example on how to use the client.

JIRA: PDC-1105

### CODE REVIEW

**Comment by ycheng-aa** [comment]
Should the "duplicit" in the title be "duplicate"?

**Comment by lubomir** [comment]
@ycheng-aa Fixed, thanks.

**Comment by erichuanggit** [comment]
@lubomir I remember you use `duplicit` in multiple place in the unit test. Not sure if it is one word from your native language :-)
:+1:

**Comment by lubomir** [comment]
@erichuanggit Yeah, that's it. Thanks for pointing this out, apparently that's a mistake I make often.

**Pull request merged**
