### PR TITLE
Refactor resource url field to id in contact app

### PR DESCRIPTION
**Pull request by erichuanggit**
Jira: PDC-883

### CODE REVIEW

**Comment by ycheng-aa** [comment]
Looks good.

**Comment by lubomir** [comment]
Exposing the `id` for contact roles does not seem very useful to me: roles are identified by the name, so knowing the `id` will give the user no new option. In my opinion contact roles should either keep the URL or only consist of the name.

Other than this, it looks good to me.

**Comment by erichuanggit** [comment]
All right, I will keep only consist of name for contact roles.

**Comment by lubomir** [comment]
With the change it looks good to me. Could you try rebasing the branch on master and force pushing to GitHub? (I would like to avoid to history with merge commits all over the place.)

**Comment by erichuanggit** [comment]
I will do that.

**Pull request merged**
