### PR TITLE
Bulk non-standard method call

### PR DESCRIPTION
**Pull request by lao605**
trap calls using methods which are not standards in HTTP/1.1 in the middleware.

### CODE REVIEW

**Comment by lubomir** [comment]
Since this pull request is from a forked repository, checking this change out locally is not completely straightforward. The way I did it is to use this command `git fetch origin pull/15/head:bulk-methods`, which creates a local branch `bulk-methods` with all commits from pull request #15. After playing around with the change and testing it I can delete the local branch without leaving anything behind.

**Comment by lao605** [comment]
wow, Travis CI seems to work pretty well~ @lubomir

**Comment by lubomir** [comment]
I don't have any more comments, this change looks good to me. Since there is some weird merging going on in these commits, I squashed and rebased them to simplify review. It is available on `PDC-758-wrong-method` branch as commit 6a84272.

**Comment by lubomir** [comment]
Merged as 6a84272.

**Pull request closed without merging**
