### PR TITLE
Add email notification as meet any error

### PR DESCRIPTION
**Pull request by erichuanggit**
This feature is disable by default. To enable it:
* cope settings_local.py.dist and rename it to settings_local.py
* make sure DEBUG set to False
* un-comment content as what describes at the end of example file

JIRA: PDC-991

### CODE REVIEW

**Comment by erichuanggit** [comment]
The error causes by:
https://github.com/pygraphviz/pygraphviz/issues/69

**Comment by erichuanggit** [comment]
It has been fixed in pygraphviz 1.3.1

**Comment by bliuredhat** [comment]
+1

**Comment by erichuanggit** [comment]
Fixed in second patch. the real email configuration will be put into deploy guide.

**Comment by erichuanggit** [comment]
just realize it is not correct to add eng-ops@redhat.com, since this change is in public code.
comment from weekly pad: add more info into the 500 error response; e.g. file ticket with eng-ops@redhat.com

**Comment by lubomir** [comment]
@erichuanggit How about moving the text to settings? There already is `EMPTY_PATCH_ERROR_RESPONSE`, so we could add `INTERNAL_SERVER_ERROR_RESPONSE`. In upstream, we could use the current text, and in internal version add the contact details.

**Comment by erichuanggit** [comment]
no more better choice. thanks for suggestion.

**Comment by lubomir** [comment]
:+1:

**Comment by xychu** [comment]
:+1:

**Pull request closed without merging**
