### PR TITLE
Rename repos resource to delivery-targets.

### PR DESCRIPTION
**Pull request by ycheng-aa**
1. Add new endpoints with same function as repos related functions.
2. Change correspoinding documentation and add deprecated message.

Didn't change repos related fields in query and response.

### CODE REVIEW

**Comment by lubomir** [comment]
All the URLs are missing trailing slashes. There will be a redirect, but the documentation should be precise.

I also feel the serializer field and filter should be renamed, but will write more about this in JIRA so that we can discuss it.

**Comment by ycheng-aa** [comment]
Fixed the URL trailing slashes in ad6bdfb8c. Thanks.

**Comment by dmach** [comment]
"delivery-target(s)" is not a good and descriptive name for the resources previously referring to "repos".
My preference is "content-delivery-repos" or "content-delivery-repositories".

**Comment by ycheng-aa** [comment]
Has been changed to content-delivery-repos

**Comment by erichuanggit** [comment]
Looks good to me.

**Comment by lubomir** [comment]
Merged as c73310cf.

**Pull request closed without merging**
