### PR TITLE
When get RPM resource, make sure linked_composes unique.

### PR DESCRIPTION
**Pull request by ycheng-aa**
JIRA: PDC-935

### CODE REVIEW

**Comment by erichuanggit** [comment]
Better have unit test cover this case.

**Comment by lubomir** [comment]
Looks good to me, but a test case would be nice.

**Comment by ycheng-aa** [comment]
@erichuanggit  @lubomir  Added the test case. Please review.

**Comment by lubomir** [comment]
:+1:

**Comment by lubomir** [comment]
Merged as d64f808e. I removed the forgotten print in test case.

**Pull request closed without merging**
