### PR TITLE
Able to set release_component_type to null.

### PR DESCRIPTION
**Pull request by erichuanggit**
JIRA: PDC-888

### CODE REVIEW

**Comment by lubomir** [comment]
I don't think this is the right fix. Based on discussion with @sochotnicky on IRC, type should not even be optional and there should rather be a default value (most likely RPM).

**Comment by erichuanggit** [comment]
Basically fixed by this bug's description. I will keep this change here until we meet together in next meeting.

**Comment by lubomir** [comment]
:+1:

**Comment by simozhan** [comment]
Good.

**Pull request closed without merging**
