### PR TITLE
Add link to change list to user menu

### PR DESCRIPTION
**Pull request by bliuredhat**
When user is logged in, the changes are accessible through this link.

JIRA: PDC-1052

### CODE REVIEW

**Comment by lubomir** [comment]
I would prefer the link after the delimiter, so that when user is logged in, the order would be Profile, Log out, Delimiter, Changes (followed by Admin if superuser).

The commit message should be reformatted, so that there is first line at most 50 characters long, followed by blank line and more detailed description. Current message breaks `git log --oneline` a bit. I would suggest something like

```
Add link to change list to user menu

When user is logged in, the changes are accessible through this link.

JIRA: PDC-1052
```

**Comment by bliuredhat** [comment]
@lubomir ,  good ideal and I rewrite it ~!
Thank you~!

**Comment by xychu** [comment]
LGTM

**Comment by lubomir** [comment]
In my opinion, the changes link should be visible for all authenticated users, not just admins.

**Comment by lubomir** [comment]
Perfect. Please rebase on master and merge.

**Pull request merged**
