### PR TITLE
Change several image inputs type from string to int.

### PR DESCRIPTION
**Pull request by simozhan**
JIRA: PDC-1101

### CODE REVIEW

**Comment by lubomir** [comment]
:+1:

By the way, are you aware the author e-mail address in the commit is a bit weird?

**Comment by lao605** [comment]
+1

**Comment by ycheng-aa** [comment]
:+1:

**Comment by erichuanggit** [comment]
It will be excellent by providing a unit test.

**Comment by simozhan** [comment]
@lubomir thanks for pointing this out. it seems the name and email address were configured automatically based on my username and hostname. Fixed it.

**Comment by simozhan** [comment]
@erichuanggit ok. added it.

**Comment by erichuanggit** [comment]
Looks good to me.

**Pull request closed without merging**
