### PR TITLE
Role count limit improvements

### PR DESCRIPTION
**Pull request by lubomir**
Accept `"unlimited"` as valid input for role count limit and fix the examples.

### CODE REVIEW

**Comment by ycheng-aa** [comment]
Looks good.

Maybe we should also change count_limit definition in model to PositiveIntegerField to not allow negative number.

**Comment by erichuanggit** [comment]
Looks good to me. 
If update `count_limit` data type, I would prefer to `PositiveSmallIntegerField`, the count of contact for specified contact_role should be less than 32767.

**Comment by lubomir** [comment]
Very good point, guys. I will change the field type.

**Comment by simozhan** [comment]
looks good

**Pull request merged**
