### PR TITLE
Add filter dist_git_branch for release component

### PR DESCRIPTION
**Pull request by erichuanggit**
JIRA: PDC-1038

### CODE REVIEW

**Comment by lubomir** [comment]
Mostly looks fine. I think it would be better if the test created the mapping directly, since it is not supposed to create the update API. But that is a minor concern. It can be merged as is.

**Comment by erichuanggit** [comment]
Just realized that dist_git_branch could also be inherited from release. Need to revise the change.

**Comment by lubomir** [comment]
Great point about inheritance. The update is not completely correct, though. Example: release has dist git branch *foo*, its component has dist git branch *bar*. Filter components with branch *foo*, the output contains the component which overrides it.

**Comment by erichuanggit** [comment]
Right. will fix in coming patch.

**Comment by lubomir** [comment]
The fix is still not correct. Admittedly, this is not a common use case, but since we don't prohibit such data, it should be handled correctly.
 * release has branch foo
 * component1 has no branch, it inherits foo from release
 * component2 has branch set to foo explicitly

Filtering components by branch foo shows only component2.

I think the previous version would work with filtering by the following expression: get all components with given branch, or components with unset dist git branch belonging to release with that branch.
```
Q(dist_git_branch__in=value) | Q(release__releasedistgitmapping__dist_git_branch__in=value,
                                 dist_git_branch__isnull=True)
```

**Comment by erichuanggit** [comment]
I will add more test cases. Thanks

**Comment by ycheng-aa** [comment]
:+1:

**Comment by lubomir** [comment]
I can't think of any more edge cases, so :+1: from me.

**Pull request closed without merging**
