### PR TITLE
Correct validation for component-groups endpoint.

### PR DESCRIPTION
**Pull request by erichuanggit**
JIRA: PDC-873

### CODE REVIEW

**Comment by lubomir** [comment]
A unit test would be great.

**Comment by erichuanggit** [comment]
there is part of unit test, for instance `test_update_group_with_other_release` line 2250, but it's not enough to cover all.

**Comment by simozhan** [comment]
Looks good for me

**Comment by lubomir** [comment]
:+1:

**Comment by lubomir** [comment]
Please squash these patches before rebasing to master and merging.

**Pull request closed without merging**
