### PR TITLE
Create read-only list of variant types.

### PR DESCRIPTION
**Pull request by simozhan**
JIRA: PDC-920

Create a new endpoint for variant types and link to it from release variants' CREATE and UPDATE

### CODE REVIEW

**Comment by erichuanggit** [comment]
Looks good to me.

**Comment by lubomir** [comment]
:+1:

**Comment by lubomir** [comment]
Since #69 is merged now, please update the documentation to not hardcode the serializer.

**Comment by simozhan** [comment]
Yes. Updated

**Comment by erichuanggit** [comment]
Looks good to me.

**Comment by lubomir** [comment]
:+1: Please squash and rebase before merging.

**Pull request closed without merging**
