### PR TITLE
Add component client plugins

### PR DESCRIPTION
**Pull request by xychu**
Including Global Component and Release Component.

### CODE REVIEW

**Comment by lubomir** [comment]
Generally looks good to me, but CLI arguments with underscores are not consistent with other plugins and generally I think dashes are more common (i.e. `--include-inactive-release` instead of `--include_inactive_release`).

**Comment by bliuredhat** [comment]
+1

**Comment by xychu** [comment]
Updated the `--include-inactive-release`.
(Force updated, my 'bad' habit to amend commit instead of adding new ones to make it easier to merge but harder to review. Hope this is the last time.)

**Comment by lubomir** [comment]
I still think the arguments should not be using underscores. There are some left. When adding it to parser, setting up `dest` should not be necessary (`plugins/component.py:144`), the resulting value should be available with underscores in the name automatically.

**Comment by erichuanggit** [comment]
Looks good to me.

**Comment by lubomir** [comment]
:+1:

**Pull request merged**
