### PR TITLE
Catch more detail excepton.

### PR DESCRIPTION
**Pull request by erichuanggit**
Catch ValueError exception for release component input.
It's not friendly to tell user internal error but log into
server's error log file without this exception block.

JIRA: PDC-905

### CODE REVIEW

**Comment by lubomir** [comment]
This is ok, but it seems to me that adding `convert_str_to_int` to line 452 would be easier and produce nicer error message.

**Comment by erichuanggit** [comment]
I was assuming there will be other fields except for id causing exception since we support id or unique_together fields input. 
`'{"release": 1, "group_type": 22,  "description": "dd",  "components":[{"release": "rhel-7.0", "global_component": "Cython", "name": "Cython"}]}'`
As a quick testing, looks like the other fields have the validation.

**Comment by simozhan** [comment]
Ok for me

**Comment by lubomir** [comment]
:+1:

**Pull request closed without merging**
